/*
 * This source file was generated by the Gradle 'init' task
 */
package inventory;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import inventory.controller.Runner;

@SuppressWarnings("unused")
class AppTest {
    @Test void appHasAGreeting() {
      Runner classUnderTest = new Runner();
      //   assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
